version: "3.7"
services:
   app:
     build: .
     command: python /usr/src/cw/yatube/manage.py runserver 0.0.0.0:8000
     volumes:
       - .:/usr/src/cw
     ports:
         - "8000:8000"
     image: app:django
     container_name: cw
